# config.yml —— 所有配置集中于此
uuid: "71d4c4c0-342b-4747-a822-57d4b878eb73"                       #输入uuid
tuic_port: "25833"                  #输入端口=确认部署
hy2_port: "26460"                   #输入端口=确认部署
reality_port: ""               #输入端口=确认部署
sni: "www.bing.com"
